"""P3-2 插件热加载测试：覆盖 spec 8.6 的 10 个 E2E 场景。

场景映射:
- test_hot_register_*: 运行时注册插件
- test_hot_unregister_*: 运行时注销插件
- test_dropin_dir_scan_*: drop-in 目录扫描
- test_mtime_polling_*: mtime 轮询检测
- test_reload_rollback_*: reload 失败回滚
- test_path_traversal_protection_*: 路径穿越防护
- test_audit_log_*: 审计日志记录
- test_no_hot_reload_flag_*: --no-hot-reload 关闭
- test_hot_loader_integration_*: 与 dispatcher 集成
- test_hot_loader_concurrent_*: 并发安全
"""

from __future__ import annotations

import os
import threading
import time
from pathlib import Path
from typing import Any

import pytest

from scripts.collaboration.plugins import PluginHotLoader, PluginStatus

# ----------------------------------------------------------------------
# 测试用 stub 插件
# ----------------------------------------------------------------------


class StubPlugin:
    """最小可识别的插件实例。"""

    def __init__(self, label: str = "stub") -> None:
        self.label = label

    def name(self) -> str:
        return self.label


# drop-in 插件文件模板（必须暴露 create_plugin()）
_DROPIN_TEMPLATE = '''
"""Drop-in plugin generated by test."""
from __future__ import annotations


class _Plugin:
    def __init__(self) -> None:
        self.tag = {tag!r}

    def name(self) -> str:
        return self.tag


def create_plugin() -> _Plugin:
    return _Plugin()
'''

_BROKEN_DROPIN_TEMPLATE = '''
"""Broken drop-in plugin (no create_plugin)."""
# 故意缺失 create_plugin() 函数
'''


def _write_dropin(filepath: Path, tag: Any) -> None:
    """写入一个合法的 drop-in 插件文件。"""
    filepath.write_text(_DROPIN_TEMPLATE.format(tag=tag), encoding="utf-8")


def _write_broken_dropin(filepath: Path) -> None:
    """写入一个损坏的 drop-in 插件文件（无 create_plugin）。"""
    filepath.write_text(_BROKEN_DROPIN_TEMPLATE, encoding="utf-8")


# ----------------------------------------------------------------------
# 1. hot_register
# ----------------------------------------------------------------------


class TestHotRegister:
    """场景: 运行时注册插件。"""

    def test_hot_register_success(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        plugin = StubPlugin("alpha")
        assert loader.hot_register("alpha", plugin) is True

        retrieved = loader.get_plugin("alpha")
        assert retrieved is plugin

    def test_hot_register_duplicate_returns_false(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("dup", StubPlugin())
        assert loader.hot_register("dup", StubPlugin()) is False

    def test_hot_register_appears_in_list(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("a", StubPlugin())
        loader.hot_register("b", StubPlugin())
        assert set(loader.list_plugins()) == {"a", "b"}

    def test_hot_register_entry_source(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("src", StubPlugin())
        entry = loader.get_entry("src")
        assert entry is not None
        assert entry.source == "hot_register"
        assert entry.status == PluginStatus.REGISTERED
        assert entry.is_active() is True


# ----------------------------------------------------------------------
# 2. hot_unregister
# ----------------------------------------------------------------------


class TestHotUnregister:
    """场景: 运行时注销插件。"""

    def test_hot_unregister_success(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("rm", StubPlugin())
        assert loader.hot_unregister("rm") is True
        assert loader.get_plugin("rm") is None
        assert "rm" not in loader.list_plugins()

    def test_hot_unregister_missing_returns_false(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        assert loader.hot_unregister("ghost") is False

    def test_hot_unregister_then_reregister(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("rt", StubPlugin("v1"))
        loader.hot_unregister("rt")
        assert loader.hot_register("rt", StubPlugin("v2")) is True
        assert loader.get_plugin("rt").label == "v2"


# ----------------------------------------------------------------------
# 3. dropin_dir_scan
# ----------------------------------------------------------------------


class TestDropinDirScan:
    """场景: drop-in 目录扫描。"""

    def test_dropin_dir_scan_loads_new(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "alpha.py", "alpha-tag")
        _write_dropin(tmp_path / "beta.py", "beta-tag")
        loader = PluginHotLoader(dropin_dir=tmp_path)

        entries = loader.scan_dropin_dir()
        assert len(entries) == 2
        names = {e.name for e in entries}
        assert names == {"alpha", "beta"}
        # 加载后可访问
        assert loader.get_plugin("alpha").name() == "alpha-tag"

    def test_dropin_dir_scan_empty_dir(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        assert loader.scan_dropin_dir() == []

    def test_dropin_dir_scan_skips_init_py(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "real.py", "real")
        (tmp_path / "__init__.py").write_text("", encoding="utf-8")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        entries = loader.scan_dropin_dir()
        assert len(entries) == 1
        assert entries[0].name == "real"

    def test_dropin_dir_scan_skips_already_registered(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "dup.py", "dropin-tag")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("dup", StubPlugin("hot"))
        # 已经 hot_register，scan 不应覆盖
        entries = loader.scan_dropin_dir()
        assert entries == []
        assert loader.get_plugin("dup").label == "hot"

    def test_dropin_dir_scan_broken_plugin_returns_none(self, tmp_path: Path) -> None:
        _write_broken_dropin(tmp_path / "broken.py")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        entries = loader.scan_dropin_dir()
        assert entries == []
        # 损坏的插件不被注册
        assert loader.get_plugin("broken") is None

    def test_dropin_dir_scan_entry_source_is_dropin(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "dp.py", "dp-tag")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.scan_dropin_dir()
        entry = loader.get_entry("dp")
        assert entry is not None
        assert entry.source == "dropin"
        assert entry.status == PluginStatus.LOADED
        assert entry.file_path != ""
        assert entry.checksum != ""

    def test_dropin_dir_scan_missing_dir_returns_empty(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path / "does_not_exist")
        assert loader.scan_dropin_dir() == []


# ----------------------------------------------------------------------
# 4. mtime_polling
# ----------------------------------------------------------------------


class TestMtimePolling:
    """场景: mtime 轮询检测。"""

    def test_mtime_polling_no_change(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "p.py", "v1")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.scan_dropin_dir()
        assert loader.reload_if_changed() == []

    def test_mtime_polling_detects_content_change(self, tmp_path: Path) -> None:
        # 注意：mtime 精度可能是秒，需要确保 mtime 变化或 checksum 变化
        fpath = tmp_path / "p.py"
        _write_dropin(fpath, "v1")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.scan_dropin_dir()
        assert loader.get_plugin("p").name() == "v1"

        # 修改内容
        time.sleep(0.05)
        _write_dropin(fpath, "v2")
        # 强制更新 mtime（某些 FS 精度低）
        os.utime(fpath, (time.time() + 5, time.time() + 5))

        reloaded = loader.reload_if_changed()
        assert "p" in reloaded
        assert loader.get_plugin("p").name() == "v2"

    def test_mtime_polling_ignores_builtin(self, tmp_path: Path) -> None:
        # builtin 不应被 reload_if_changed 触碰
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.register_builtin("builtin", StubPlugin("v1"))
        assert loader.reload_if_changed() == []
        # builtin 仍在
        assert loader.get_plugin("builtin").label == "v1"


# ----------------------------------------------------------------------
# 5. reload_rollback
# ----------------------------------------------------------------------


class TestReloadRollback:
    """场景: reload 失败回滚（保留旧实例）。"""

    def test_reload_rollback_keeps_old_instance(self, tmp_path: Path) -> None:
        fpath = tmp_path / "p.py"
        _write_dropin(fpath, "v1")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.scan_dropin_dir()
        old_instance = loader.get_plugin("p")
        assert old_instance.name() == "v1"

        # 修改为损坏的插件
        time.sleep(0.05)
        _write_broken_dropin(fpath)
        os.utime(fpath, (time.time() + 5, time.time() + 5))

        # reload 应失败，但保留旧实例
        reloaded = loader.reload_if_changed()
        assert "p" not in reloaded  # 未成功重载
        # 旧实例仍可用
        assert loader.get_plugin("p") is old_instance
        assert loader.get_plugin("p").name() == "v1"

    def test_reload_rollback_logs_failure(self, tmp_path: Path) -> None:
        fpath = tmp_path / "p.py"
        _write_dropin(fpath, "v1")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.scan_dropin_dir()
        loader.clear_audit_log()

        time.sleep(0.05)
        _write_broken_dropin(fpath)
        os.utime(fpath, (time.time() + 5, time.time() + 5))

        loader.reload_if_changed()
        audits = loader.get_audit_log()
        reload_audits = [a for a in audits if a["method"] == "reload"]
        assert any(a["success"] is False for a in reload_audits)


# ----------------------------------------------------------------------
# 6. path_traversal_protection
# ----------------------------------------------------------------------


class TestPathTraversalProtection:
    """场景: 路径穿越防护。"""

    def test_path_traversal_invalid_suffix_blocked(self, tmp_path: Path) -> None:
        # 非 .py 后缀的文件不会被加载
        (tmp_path / "evil.txt").write_text("print('evil')", encoding="utf-8")
        (tmp_path / "evil.pyc").write_text("binary", encoding="utf-8")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        entries = loader.scan_dropin_dir()
        assert entries == []

    def test_path_traversal_symlink_outside_blocked(self, tmp_path: Path) -> None:
        # 创建 dropin 目录外的真实文件
        outside = tmp_path.parent / "outside_target.py"
        try:
            _write_dropin(outside, "outside")
            # 在 dropin 目录内创建符号链接
            link_path = tmp_path / "link.py"
            link_path.symlink_to(outside)

            loader = PluginHotLoader(dropin_dir=tmp_path)
            entries = loader.scan_dropin_dir()
            # 符号链接 resolve() 后指向 dropin 目录外，应被拒绝
            assert entries == []
        finally:
            if outside.exists():
                outside.unlink()

    def test_path_traversal_file_size_limit(self, tmp_path: Path) -> None:
        # 创建超大文件（>1MB）
        big_file = tmp_path / "big.py"
        big_file.write_text("# big\n" + "x" * (1024 * 1024 + 100), encoding="utf-8")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        entries = loader.scan_dropin_dir()
        assert entries == []

    def test_path_traversal_normal_file_allowed(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "ok.py", "ok")
        loader = PluginHotLoader(dropin_dir=tmp_path)
        entries = loader.scan_dropin_dir()
        assert len(entries) == 1
        assert entries[0].name == "ok"


# ----------------------------------------------------------------------
# 7. audit_log
# ----------------------------------------------------------------------


class TestAuditLog:
    """场景: 审计日志记录。"""

    def test_audit_log_hot_register(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("a", StubPlugin())
        audits = loader.get_audit_log()
        assert any(a["method"] == "hot_register" and a["name"] == "a" and a["success"] for a in audits)

    def test_audit_log_hot_unregister(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("a", StubPlugin())
        loader.clear_audit_log()
        loader.hot_unregister("a")
        audits = loader.get_audit_log()
        assert any(a["method"] == "hot_unregister" and a["success"] for a in audits)

    def test_audit_log_register_builtin(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.register_builtin("b", StubPlugin())
        audits = loader.get_audit_log()
        assert any(a["method"] == "register_builtin" and a["success"] for a in audits)

    def test_audit_log_failed_register(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        loader.hot_register("a", StubPlugin())
        loader.clear_audit_log()
        loader.hot_register("a", StubPlugin())  # 重复注册失败
        audits = loader.get_audit_log()
        assert any(a["method"] == "hot_register" and not a["success"] for a in audits)

    def test_audit_log_external_logger_invoked(self, tmp_path: Path) -> None:
        class CapturingAuditLogger:
            def __init__(self) -> None:
                self.records: list[dict[str, Any]] = []

            def log_plugin_op(self, **kwargs: Any) -> None:
                self.records.append(kwargs)

        external = CapturingAuditLogger()
        loader = PluginHotLoader(dropin_dir=tmp_path, audit_logger=external)
        loader.hot_register("x", StubPlugin())
        assert len(external.records) == 1
        assert external.records[0]["method"] == "hot_register"
        assert external.records[0]["name"] == "x"
        assert external.records[0]["success"] is True


# ----------------------------------------------------------------------
# 8. no_hot_reload_flag
# ----------------------------------------------------------------------


class TestNoHotReloadFlag:
    """场景: --no-hot-reload 关闭动态加载。"""

    def test_no_hot_reload_blocks_hot_register(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path, no_hot_reload=True)
        assert loader.hot_register("a", StubPlugin()) is False
        assert loader.get_plugin("a") is None

    def test_no_hot_reload_blocks_hot_unregister(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path, no_hot_reload=True)
        # 即使存在也不能 unregister
        loader.register_builtin("b", StubPlugin())
        assert loader.hot_unregister("b") is False
        # builtin 仍在
        assert loader.get_plugin("b") is not None

    def test_no_hot_reload_allows_builtin(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path, no_hot_reload=True)
        assert loader.register_builtin("b", StubPlugin()) is True
        assert loader.get_plugin("b") is not None

    def test_no_hot_reload_blocks_scan_dropin(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "p.py", "p")
        loader = PluginHotLoader(dropin_dir=tmp_path, no_hot_reload=True)
        assert loader.scan_dropin_dir() == []

    def test_no_hot_reload_blocks_reload(self, tmp_path: Path) -> None:
        _write_dropin(tmp_path / "p.py", "p")
        loader = PluginHotLoader(dropin_dir=tmp_path, no_hot_reload=True)
        # 先用 no_hot_reload=False 加载，再切换会破坏状态；
        # 这里直接验证 no_hot_reload=True 时 reload 返回空
        assert loader.reload_if_changed() == []

    def test_no_hot_reload_property(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path, no_hot_reload=True)
        assert loader.no_hot_reload is True


# ----------------------------------------------------------------------
# 9. hot_loader_integration
# ----------------------------------------------------------------------


class TestHotLoaderIntegration:
    """场景: 与 dispatcher 集成（消除幽灵功能）。"""

    def test_plugins_disabled_by_default(self) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(enable_warmup=False, enable_memory=False, enable_skillify=False)
        assert d.plugins_enabled is False
        assert d.plugin_hot_loader is None

    def test_plugins_enabled_creates_loader(self, tmp_path: Path) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=str(tmp_path),
            plugins_enabled=True,
        )
        assert d.plugins_enabled is True
        assert d.plugin_hot_loader is not None

    def test_register_plugin_without_loader_raises(self) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(enable_warmup=False, enable_memory=False, enable_skillify=False)
        with pytest.raises(RuntimeError, match="PluginHotLoader not enabled"):
            d.register_plugin("x", StubPlugin())

    def test_unregister_plugin_without_loader_raises(self) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(enable_warmup=False, enable_memory=False, enable_skillify=False)
        with pytest.raises(RuntimeError, match="PluginHotLoader not enabled"):
            d.unregister_plugin("x")

    def test_get_plugin_without_loader_raises(self) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(enable_warmup=False, enable_memory=False, enable_skillify=False)
        with pytest.raises(RuntimeError, match="PluginHotLoader not enabled"):
            d.get_plugin("x")

    def test_list_plugins_without_loader_raises(self) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(enable_warmup=False, enable_memory=False, enable_skillify=False)
        with pytest.raises(RuntimeError, match="PluginHotLoader not enabled"):
            d.list_plugins()

    def test_scan_plugins_without_loader_raises(self) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(enable_warmup=False, enable_memory=False, enable_skillify=False)
        with pytest.raises(RuntimeError, match="PluginHotLoader not enabled"):
            d.scan_plugins()

    def test_reload_plugins_without_loader_raises(self) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(enable_warmup=False, enable_memory=False, enable_skillify=False)
        with pytest.raises(RuntimeError, match="PluginHotLoader not enabled"):
            d.reload_plugins()

    def test_dispatcher_register_plugin_works_when_enabled(self, tmp_path: Path) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=str(tmp_path),
            plugins_enabled=True,
        )
        plugin = StubPlugin("via-dispatcher")
        assert d.register_plugin("dp", plugin) is True
        assert d.get_plugin("dp") is plugin
        assert "dp" in d.list_plugins()

    def test_dispatcher_builtin_plugin_works_with_no_hot_reload(self, tmp_path: Path) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        d = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=str(tmp_path),
            plugins_enabled=True,
            plugins_no_hot_reload=True,
        )
        # no_hot_reload=True 时，hot_register 被阻止
        assert d.register_plugin("hot", StubPlugin()) is False
        # 但 register_builtin 仍可用
        assert d.register_builtin_plugin("builtin", StubPlugin()) is True
        assert d.get_plugin("builtin") is not None

    def test_dispatcher_scan_and_reload_plugins(self, tmp_path: Path) -> None:
        from scripts.collaboration.dispatcher import MultiAgentDispatcher

        # 用单独的 dropin 目录
        dropin = tmp_path / "dropin"
        dropin.mkdir()
        _write_dropin(dropin / "extra.py", "extra-tag")

        d = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=str(tmp_path / "run"),
            plugins_enabled=True,
            plugins_dropin_dir=str(dropin),
        )
        # 扫描加载
        entries = d.scan_plugins()
        assert len(entries) == 1
        assert entries[0].name == "extra"
        # 再次扫描不会重复加载
        assert d.scan_plugins() == []
        # reload 无变化
        assert d.reload_plugins() == []


# ----------------------------------------------------------------------
# 10. hot_loader_concurrent
# ----------------------------------------------------------------------


class TestHotLoaderConcurrent:
    """场景: 并发安全（threading.RLock）。"""

    def test_concurrent_register_distinct_names(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        n_threads = 10
        n_per_thread = 20
        results: list[bool] = []
        results_lock = threading.Lock()

        def worker(tid: int) -> None:
            local_results: list[bool] = []
            for i in range(n_per_thread):
                name = f"t{tid}-p{i}"
                local_results.append(loader.hot_register(name, StubPlugin(name)))
            with results_lock:
                results.extend(local_results)

        threads = [threading.Thread(target=worker, args=(t,)) for t in range(n_threads)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        # 所有注册都应成功（名字互不冲突）
        assert all(results)
        assert len(loader.list_plugins()) == n_threads * n_per_thread

    def test_concurrent_register_same_name_only_one_wins(self, tmp_path: Path) -> None:
        loader = PluginHotLoader(dropin_dir=tmp_path)
        n_threads = 20
        winners: list[bool] = []
        winners_lock = threading.Lock()

        def worker() -> None:
            ok = loader.hot_register("contended", StubPlugin())
            with winners_lock:
                winners.append(ok)

        threads = [threading.Thread(target=worker) for _ in range(n_threads)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        # 只有一个线程成功
        assert sum(1 for w in winners if w) == 1
        assert loader.get_plugin("contended") is not None

    def test_concurrent_scan_and_register(self, tmp_path: Path) -> None:
        # 在 dropin 目录写入文件
        for i in range(5):
            _write_dropin(tmp_path / f"f{i}.py", f"tag-{i}")

        loader = PluginHotLoader(dropin_dir=tmp_path)
        errors: list[Exception] = []
        errors_lock = threading.Lock()

        def scan_worker() -> None:
            try:
                loader.scan_dropin_dir()
            except Exception as e:  # noqa: BLE001
                with errors_lock:
                    errors.append(e)

        def register_worker() -> None:
            try:
                for i in range(10):
                    loader.hot_register(f"hot-{i}", StubPlugin())
            except Exception as e:  # noqa: BLE001
                with errors_lock:
                    errors.append(e)

        threads = [
            threading.Thread(target=scan_worker),
            threading.Thread(target=scan_worker),
            threading.Thread(target=register_worker),
            threading.Thread(target=register_worker),
        ]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        assert errors == []
        # 至少加载了一些 drop-in
        dropin_loaded = [n for n in loader.list_plugins() if n.startswith("f")]
        assert len(dropin_loaded) > 0
        # hot_register 也注册了
        hot_loaded = [n for n in loader.list_plugins() if n.startswith("hot-")]
        assert len(hot_loaded) > 0
