#!/usr/bin/env python3
"""PluginHotLoader + Dispatcher Integration Tests (V4.2.1 P2-4 — Test Pyramid Improvement).

End-to-end integration tests for PluginHotLoader + MultiAgentDispatcher
cross-module interaction. Verifies that the plugin hot-loading subsystem
wires correctly into the dispatcher across the full lifecycle:

    MultiAgentDispatcher(plugins_enabled=True, plugins_dropin_dir=...)
      → ComponentFactory creates PluginHotLoader
        → scan_plugins() → scan_dropin_dir() → importlib load (create_plugin)
        → reload_plugins() → reload_if_changed() (mtime + checksum, rollback)
      → register_plugin / unregister_plugin / register_builtin_plugin
      → get_plugin / list_plugins

These tests focus on CROSS-MODULE interactions (dispatcher ↔ loader boundary,
config propagation, real .py file drop-in loading, reload rollback). Unit-level
behavior of PluginHotLoader in isolation is covered by
tests/test_plugins_hot_loader.py.

Test categories:
    T1: PluginHotLoader discovery wired through dispatcher
    T2: Plugin registration with dispatcher (hot_register / builtin)
    T3: Hot-reload integration (modify .py → reload → new instance)
    T4: plugins_no_hot_reload mode integration
    T5: Disabled mode integration (plugins_enabled=False → loader None)
    T6: Multiple plugins integration (multi-file scan, coexistence)
    T7: Edge cases + graceful degradation (empty, malformed, raising, rollback)
"""

from __future__ import annotations

import os
import shutil
import sys
import tempfile
import time
import unittest
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from scripts.collaboration.dispatcher import MultiAgentDispatcher
from scripts.collaboration.plugins import PluginEntry, PluginHotLoader, PluginStatus

# ---------------------------------------------------------------------------
# Drop-in plugin file templates + helpers
# ---------------------------------------------------------------------------

_DROPIN_TEMPLATE = '''"""Drop-in plugin generated by integration test."""
from __future__ import annotations


class _Plugin:
    def __init__(self) -> None:
        self.tag = {tag!r}

    def name(self) -> str:
        return self.tag


def create_plugin() -> _Plugin:
    return _Plugin()
'''

_BROKEN_DROPIN_TEMPLATE = '''"""Broken drop-in plugin (no create_plugin)."""
# Intentionally missing create_plugin().
'''

_RAISING_DROPIN_TEMPLATE = '''"""Drop-in plugin whose create_plugin raises RuntimeError."""
from __future__ import annotations


def create_plugin():
    raise RuntimeError("plugin init failed")
'''


def _write_dropin(filepath: Path, tag: str) -> None:
    """Write a valid drop-in plugin file exposing create_plugin()."""
    filepath.write_text(_DROPIN_TEMPLATE.format(tag=tag), encoding="utf-8")


def _write_broken_dropin(filepath: Path) -> None:
    """Write a malformed drop-in plugin (no create_plugin function)."""
    filepath.write_text(_BROKEN_DROPIN_TEMPLATE, encoding="utf-8")


def _write_raising_dropin(filepath: Path) -> None:
    """Write a drop-in plugin whose create_plugin() raises RuntimeError."""
    filepath.write_text(_RAISING_DROPIN_TEMPLATE, encoding="utf-8")


def _bump_mtime(filepath: Path) -> None:
    """Force a filesystem mtime change (robust across low-precision FSes)."""
    future = time.time() + 5
    os.utime(filepath, (future, future))


class _StubPlugin:
    """Minimal plugin instance used for register_plugin / register_builtin tests."""

    def __init__(self, label: str = "stub") -> None:
        self.label = label

    def name(self) -> str:
        return self.label


# ---------------------------------------------------------------------------
# T1: PluginHotLoader discovery wired through dispatcher
# ---------------------------------------------------------------------------


class T1_PluginDiscoveryIntegration(unittest.TestCase):
    """T1: PluginHotLoader discovery wired through the dispatcher."""

    def setUp(self) -> None:
        self._work_dir = tempfile.mkdtemp(prefix="plugin_disc_")
        self._dropin = Path(self._work_dir) / "dropin"
        self._dropin.mkdir()
        self.disp = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=self._work_dir,
            plugins_enabled=True,
            plugins_dropin_dir=str(self._dropin),
        )

    def tearDown(self) -> None:
        self.disp.shutdown()
        shutil.rmtree(self._work_dir, ignore_errors=True)

    def test_01_dispatcher_scan_loads_dropin_py_file(self) -> None:
        """Verify: dispatcher.scan_plugins() loads a real .py drop-in via importlib."""
        _write_dropin(self._dropin / "alpha.py", "alpha-tag")
        entries = self.disp.scan_plugins()
        self.assertEqual(len(entries), 1)
        self.assertIsInstance(entries[0], PluginEntry)
        self.assertEqual(entries[0].name, "alpha")
        # Loaded instance is reachable through the dispatcher
        plugin = self.disp.get_plugin("alpha")
        self.assertIsNotNone(plugin)
        self.assertEqual(plugin.name(), "alpha-tag")

    def test_02_default_dropin_dir_created_under_persist_dir(self) -> None:
        """Verify: plugins_dropin_dir=None → factory creates persist_dir/plugins_extra."""
        work_dir = tempfile.mkdtemp(prefix="plugin_default_")
        try:
            disp = MultiAgentDispatcher(
                enable_warmup=False,
                enable_memory=False,
                enable_skillify=False,
                persist_dir=work_dir,
                plugins_enabled=True,
            )
            self.assertIsInstance(disp.plugin_hot_loader, PluginHotLoader)
            expected = (Path(work_dir) / "plugins_extra").resolve()
            self.assertEqual(disp.plugin_hot_loader.dropin_dir, expected)
            self.assertTrue(expected.exists(), "Default drop-in dir must be created by factory")
            disp.shutdown()
        finally:
            shutil.rmtree(work_dir, ignore_errors=True)

    def test_03_custom_dropin_dir_propagated_to_loader(self) -> None:
        """Verify: plugins_dropin_dir kwarg reaches PluginHotLoader.dropin_dir."""
        self.assertEqual(
            self.disp.plugin_hot_loader.dropin_dir,
            self._dropin.resolve(),
        )

    def test_04_scan_skips_init_py_and_non_py_files(self) -> None:
        """Verify: scan ignores __init__.py and non-.py files, loads real plugins only."""
        _write_dropin(self._dropin / "real.py", "real")
        (self._dropin / "__init__.py").write_text("", encoding="utf-8")
        (self._dropin / "notes.txt").write_text("not a plugin", encoding="utf-8")
        entries = self.disp.scan_plugins()
        self.assertEqual(len(entries), 1)
        self.assertEqual(entries[0].name, "real")


# ---------------------------------------------------------------------------
# T2: Plugin registration with dispatcher
# ---------------------------------------------------------------------------


class T2_PluginRegistrationIntegration(unittest.TestCase):
    """T2: register_plugin / unregister_plugin / register_builtin_plugin via dispatcher."""

    def setUp(self) -> None:
        self._work_dir = tempfile.mkdtemp(prefix="plugin_reg_")
        self._dropin = Path(self._work_dir) / "dropin"
        self._dropin.mkdir()
        self.disp = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=self._work_dir,
            plugins_enabled=True,
            plugins_dropin_dir=str(self._dropin),
        )

    def tearDown(self) -> None:
        self.disp.shutdown()
        shutil.rmtree(self._work_dir, ignore_errors=True)

    def test_01_register_plugin_returns_true_and_retrievable(self) -> None:
        """Verify: register_plugin() returns True and get_plugin() returns same instance."""
        plugin = _StubPlugin("reg")
        self.assertTrue(self.disp.register_plugin("reg", plugin))
        self.assertIs(self.disp.get_plugin("reg"), plugin)

    def test_02_registered_plugin_invokable_via_dispatcher(self) -> None:
        """Verify: plugin retrieved via dispatcher is callable (method returns label)."""
        self.disp.register_plugin("p", _StubPlugin("hello"))
        plugin = self.disp.get_plugin("p")
        self.assertIsNotNone(plugin)
        self.assertEqual(plugin.name(), "hello")

    def test_03_register_duplicate_returns_false(self) -> None:
        """Verify: registering the same name twice returns False (no overwrite)."""
        self.assertTrue(self.disp.register_plugin("dup", _StubPlugin("v1")))
        self.assertFalse(self.disp.register_plugin("dup", _StubPlugin("v2")))
        # Original instance preserved
        self.assertEqual(self.disp.get_plugin("dup").name(), "v1")

    def test_04_unregister_plugin_removes_it(self) -> None:
        """Verify: unregister_plugin() removes the plugin from the loader."""
        self.disp.register_plugin("rm", _StubPlugin())
        self.assertTrue(self.disp.unregister_plugin("rm"))
        self.assertIsNone(self.disp.get_plugin("rm"))
        self.assertNotIn("rm", self.disp.list_plugins())

    def test_05_builtin_and_hot_registered_coexist(self) -> None:
        """Verify: register_builtin_plugin and register_plugin populate the same registry."""
        self.assertTrue(self.disp.register_builtin_plugin("builtin", _StubPlugin("b")))
        self.assertTrue(self.disp.register_plugin("hot", _StubPlugin("h")))
        self.assertEqual(set(self.disp.list_plugins()), {"builtin", "hot"})
        # Sources differ between the two registration paths
        builtin_entry = self.disp.plugin_hot_loader.get_entry("builtin")
        hot_entry = self.disp.plugin_hot_loader.get_entry("hot")
        self.assertEqual(builtin_entry.source, "builtin")
        self.assertEqual(hot_entry.source, "hot_register")


# ---------------------------------------------------------------------------
# T3: Hot-reload integration
# ---------------------------------------------------------------------------


class T3_HotReloadIntegration(unittest.TestCase):
    """T3: Hot-reload cycle through dispatcher (modify .py → reload → new instance)."""

    def setUp(self) -> None:
        self._work_dir = tempfile.mkdtemp(prefix="plugin_reload_")
        self._dropin = Path(self._work_dir) / "dropin"
        self._dropin.mkdir()
        self.disp = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=self._work_dir,
            plugins_enabled=True,
            plugins_dropin_dir=str(self._dropin),
        )

    def tearDown(self) -> None:
        self.disp.shutdown()
        shutil.rmtree(self._work_dir, ignore_errors=True)

    def test_01_reload_no_changes_returns_empty(self) -> None:
        """Verify: reload_plugins() with unchanged files returns an empty list."""
        _write_dropin(self._dropin / "p.py", "v1")
        self.disp.scan_plugins()
        self.assertEqual(self.disp.reload_plugins(), [])

    def test_02_modify_content_triggers_reload(self) -> None:
        """Verify: modifying plugin content → reload_plugins() reports it and updates behavior."""
        fpath = self._dropin / "p.py"
        _write_dropin(fpath, "v1")
        self.disp.scan_plugins()
        self.assertEqual(self.disp.get_plugin("p").name(), "v1")

        time.sleep(0.05)
        _write_dropin(fpath, "v2")
        _bump_mtime(fpath)

        reloaded = self.disp.reload_plugins()
        self.assertEqual(reloaded, ["p"])
        self.assertEqual(self.disp.get_plugin("p").name(), "v2")

    def test_03_reloaded_instance_is_a_new_object(self) -> None:
        """Verify: reload swaps the plugin instance (new object, not mutated in place)."""
        fpath = self._dropin / "p.py"
        _write_dropin(fpath, "v1")
        self.disp.scan_plugins()
        old_instance = self.disp.get_plugin("p")

        time.sleep(0.05)
        _write_dropin(fpath, "v2")
        _bump_mtime(fpath)
        self.disp.reload_plugins()

        new_instance = self.disp.get_plugin("p")
        self.assertIsNot(old_instance, new_instance)

    def test_04_reload_only_affects_changed_plugins(self) -> None:
        """Verify: reload_plugins() returns only the plugins whose content changed."""
        a = self._dropin / "a.py"
        b = self._dropin / "b.py"
        _write_dropin(a, "a1")
        _write_dropin(b, "b1")
        self.disp.scan_plugins()

        time.sleep(0.05)
        _write_dropin(b, "b2")
        _bump_mtime(b)

        reloaded = self.disp.reload_plugins()
        self.assertEqual(reloaded, ["b"])
        self.assertEqual(self.disp.get_plugin("a").name(), "a1")  # unchanged
        self.assertEqual(self.disp.get_plugin("b").name(), "b2")  # reloaded


# ---------------------------------------------------------------------------
# T4: plugins_no_hot_reload mode integration
# ---------------------------------------------------------------------------


class T4_NoHotReloadModeIntegration(unittest.TestCase):
    """T4: plugins_no_hot_reload=True flag propagates dispatcher → loader → behavior."""

    def setUp(self) -> None:
        self._work_dir = tempfile.mkdtemp(prefix="plugin_nohr_")
        self._dropin = Path(self._work_dir) / "dropin"
        self._dropin.mkdir()
        self.disp = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=self._work_dir,
            plugins_enabled=True,
            plugins_dropin_dir=str(self._dropin),
            plugins_no_hot_reload=True,
        )

    def tearDown(self) -> None:
        self.disp.shutdown()
        shutil.rmtree(self._work_dir, ignore_errors=True)

    def test_01_no_hot_reload_propagates_to_loader(self) -> None:
        """Verify: dispatcher plugins_no_hot_reload=True → loader.no_hot_reload is True."""
        self.assertTrue(self.disp.plugin_hot_loader.no_hot_reload)

    def test_02_register_plugin_blocked_returns_false(self) -> None:
        """Verify: register_plugin() returns False under no_hot_reload (hot path blocked)."""
        self.assertFalse(self.disp.register_plugin("hot", _StubPlugin()))
        self.assertIsNone(self.disp.get_plugin("hot"))

    def test_03_register_builtin_allowed_under_no_hot_reload(self) -> None:
        """Verify: register_builtin_plugin() still works under no_hot_reload."""
        self.assertTrue(self.disp.register_builtin_plugin("b", _StubPlugin("b")))
        self.assertIsNotNone(self.disp.get_plugin("b"))
        self.assertIn("b", self.disp.list_plugins())

    def test_04_scan_and_reload_blocked_when_no_hot_reload(self) -> None:
        """Verify: scan_plugins() and reload_plugins() are no-ops under no_hot_reload."""
        _write_dropin(self._dropin / "p.py", "p")
        self.assertEqual(self.disp.scan_plugins(), [])
        self.assertEqual(self.disp.reload_plugins(), [])
        self.assertIsNone(self.disp.get_plugin("p"))


# ---------------------------------------------------------------------------
# T5: Disabled mode integration
# ---------------------------------------------------------------------------


class T5_DisabledModeIntegration(unittest.TestCase):
    """T5: plugins_enabled=False → loader stays None and all plugin APIs raise."""

    def setUp(self) -> None:
        self._work_dir = tempfile.mkdtemp(prefix="plugin_disabled_")
        self.disp = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=self._work_dir,
        )

    def tearDown(self) -> None:
        self.disp.shutdown()
        shutil.rmtree(self._work_dir, ignore_errors=True)

    def test_01_disabled_by_default_loader_is_none(self) -> None:
        """Verify: plugins_enabled defaults to False and plugin_hot_loader is None."""
        self.assertFalse(self.disp.plugins_enabled)
        self.assertIsNone(self.disp.plugin_hot_loader)

    def test_02_register_plugin_raises_runtime_error(self) -> None:
        """Verify: register_plugin() raises RuntimeError when plugins are disabled."""
        with self.assertRaises(RuntimeError) as ctx:
            self.disp.register_plugin("x", _StubPlugin())
        self.assertIn("PluginHotLoader not enabled", str(ctx.exception))

    def test_03_scan_plugins_raises_runtime_error(self) -> None:
        """Verify: scan_plugins() raises RuntimeError when plugins are disabled."""
        with self.assertRaises(RuntimeError):
            self.disp.scan_plugins()

    def test_04_get_plugin_raises_runtime_error(self) -> None:
        """Verify: get_plugin() raises RuntimeError when plugins are disabled."""
        with self.assertRaises(RuntimeError):
            self.disp.get_plugin("anything")


# ---------------------------------------------------------------------------
# T6: Multiple plugins integration
# ---------------------------------------------------------------------------


class T6_MultiplePluginsIntegration(unittest.TestCase):
    """T6: Multiple drop-in plugins — scan, listing, and coexistence."""

    def setUp(self) -> None:
        self._work_dir = tempfile.mkdtemp(prefix="plugin_multi_")
        self._dropin = Path(self._work_dir) / "dropin"
        self._dropin.mkdir()
        self.disp = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=self._work_dir,
            plugins_enabled=True,
            plugins_dropin_dir=str(self._dropin),
        )

    def tearDown(self) -> None:
        self.disp.shutdown()
        shutil.rmtree(self._work_dir, ignore_errors=True)

    def test_01_multiple_files_loaded_in_one_scan(self) -> None:
        """Verify: scan_plugins() loads all .py files in a single pass."""
        _write_dropin(self._dropin / "a.py", "a")
        _write_dropin(self._dropin / "b.py", "b")
        _write_dropin(self._dropin / "c.py", "c")
        entries = self.disp.scan_plugins()
        self.assertEqual(len(entries), 3)
        self.assertEqual({e.name for e in entries}, {"a", "b", "c"})
        for e in entries:
            self.assertEqual(e.status, PluginStatus.LOADED)
            self.assertEqual(e.source, "dropin")

    def test_02_list_plugins_returns_all_names(self) -> None:
        """Verify: list_plugins() reports every loaded drop-in."""
        _write_dropin(self._dropin / "a.py", "a")
        _write_dropin(self._dropin / "b.py", "b")
        self.disp.scan_plugins()
        self.assertEqual(set(self.disp.list_plugins()), {"a", "b"})

    def test_03_second_scan_returns_empty(self) -> None:
        """Verify: a repeat scan_plugins() does not reload already-loaded plugins."""
        _write_dropin(self._dropin / "p.py", "p")
        self.assertEqual(len(self.disp.scan_plugins()), 1)
        self.assertEqual(self.disp.scan_plugins(), [])

    def test_04_builtin_and_dropin_coexist_in_registry(self) -> None:
        """Verify: a builtin plugin and a drop-in plugin coexist in list_plugins()."""
        self.disp.register_builtin_plugin("builtin", _StubPlugin("b"))
        _write_dropin(self._dropin / "drop.py", "d")
        self.disp.scan_plugins()
        self.assertEqual(set(self.disp.list_plugins()), {"builtin", "drop"})


# ---------------------------------------------------------------------------
# T7: Edge cases + graceful degradation
# ---------------------------------------------------------------------------


class T7_EdgeCasesAndGracefulDegradationIntegration(unittest.TestCase):
    """T7: Empty dir, malformed plugin, raising plugin, reload rollback, audit log."""

    def setUp(self) -> None:
        self._work_dir = tempfile.mkdtemp(prefix="plugin_edge_")
        self._dropin = Path(self._work_dir) / "dropin"
        self._dropin.mkdir()
        self.disp = MultiAgentDispatcher(
            enable_warmup=False,
            enable_memory=False,
            enable_skillify=False,
            persist_dir=self._work_dir,
            plugins_enabled=True,
            plugins_dropin_dir=str(self._dropin),
        )

    def tearDown(self) -> None:
        self.disp.shutdown()
        shutil.rmtree(self._work_dir, ignore_errors=True)

    def test_01_empty_dropin_dir_scan_returns_empty(self) -> None:
        """Verify: scan_plugins() on an empty drop-in dir returns an empty list."""
        self.assertEqual(self.disp.scan_plugins(), [])
        self.assertEqual(self.disp.list_plugins(), [])

    def test_02_malformed_plugin_no_create_plugin_skipped(self) -> None:
        """Verify: a drop-in missing create_plugin() is skipped (graceful, no crash)."""
        _write_broken_dropin(self._dropin / "broken.py")
        entries = self.disp.scan_plugins()
        self.assertEqual(entries, [])
        self.assertIsNone(self.disp.get_plugin("broken"))

    def test_03_create_plugin_raising_runtime_error_returns_none(self) -> None:
        """Verify: create_plugin() raising RuntimeError is swallowed; plugin not registered."""
        _write_raising_dropin(self._dropin / "raising.py")
        entries = self.disp.scan_plugins()
        self.assertEqual(entries, [])
        self.assertIsNone(self.disp.get_plugin("raising"))

    def test_04_reload_rollback_keeps_old_instance(self) -> None:
        """Verify: reload of a broken update keeps the previous working instance."""
        fpath = self._dropin / "p.py"
        _write_dropin(fpath, "v1")
        self.disp.scan_plugins()
        old_instance = self.disp.get_plugin("p")
        self.assertEqual(old_instance.name(), "v1")

        time.sleep(0.05)
        _write_broken_dropin(fpath)
        _bump_mtime(fpath)

        reloaded = self.disp.reload_plugins()
        self.assertNotIn("p", reloaded)  # reload failed
        # Old instance preserved (rollback)
        self.assertIs(self.disp.get_plugin("p"), old_instance)
        self.assertEqual(self.disp.get_plugin("p").name(), "v1")

    def test_05_audit_log_records_dispatcher_reload(self) -> None:
        """Verify: loader audit log records a successful reload triggered via dispatcher."""
        fpath = self._dropin / "p.py"
        _write_dropin(fpath, "v1")
        self.disp.scan_plugins()
        self.disp.plugin_hot_loader.clear_audit_log()

        time.sleep(0.05)
        _write_dropin(fpath, "v2")
        _bump_mtime(fpath)
        self.disp.reload_plugins()

        audits = self.disp.plugin_hot_loader.get_audit_log()
        reload_audits = [a for a in audits if a["method"] == "reload"]
        self.assertTrue(
            any(a["success"] for a in reload_audits),
            f"Expected successful reload audit entry, got: {reload_audits}",
        )


if __name__ == "__main__":
    unittest.main()
