#!/usr/bin/env python3
"""
协作系统数据模型 — 生命周期执行与回顾相关定义。

本模块包含执行计划（ExecutionPlan / TaskBatch / ScheduleResult）以及
V3.7.0 "Anchor & Retrospect" 的目标对齐、漂移检测、回顾报告等数据结构，
用于 BatchScheduler、AnchorChecker、RetrospectiveEngine 等组件。
"""

import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from .models_base import TaskDefinition, WorkerResult


@dataclass
class ExecutionPlan:
    """Complete execution plan generated by Coordinator.plan_task().

    Contains all task batches with scheduling information for
    BatchScheduler to execute.

    Attributes:
        plan_id: Unique plan identifier (auto-generated)
        batches: List of TaskBatch objects (parallel/sequential groups)
        total_tasks: Total number of tasks across all batches
        estimated_parallelism: Estimated parallelism level 0.0-1.0

    Example:
        >>> plan = ExecutionPlan(
        ...     batches=[parallel_batch],
        ...     total_tasks=3,
        ...     estimated_parallelism=1.0,
        ... )
    """
    plan_id: str = field(default_factory=lambda: f"plan-{uuid.uuid4().hex[:8]}")
    batches: list[Any] = field(default_factory=list)
    total_tasks: int = 0
    estimated_parallelism: float = 0.0


class BatchMode(Enum):
    """Task batch execution mode.

    Determines how tasks within a batch are executed by BatchScheduler.

    Attributes:
        PARALLEL: Execute all tasks concurrently (up to max_concurrency)
        SERIAL: Execute tasks one-by-one in order with retry support
    """
    PARALLEL = "parallel"
    SERIAL = "serial"


@dataclass
class TaskBatch:
    """Group of tasks to be executed together.

    Batches are the scheduling unit in ExecutionPlan. Each batch
    has a mode (PARALLEL/SERIAL) and contains related TaskDefinitions.

    Attributes:
        batch_id: Unique batch identifier (auto-generated)
        mode: Execution mode (PARALLEL or SERIAL)
        tasks: List of task definitions in this batch
        max_concurrency: Max parallel tasks for PARALLEL mode (default: 5)
        dependencies: List of prerequisite batch IDs that must complete first
        timeout_seconds: Maximum execution time for entire batch (default: 600)

    Example:
        >>> batch = TaskBatch(
        ...     mode=BatchMode.PARALLEL,
        ...     tasks=[task1, task2, task3],
        ...     max_concurrency=3,
        ... )
    """
    batch_id: str = field(default_factory=lambda: f"batch-{uuid.uuid4().hex[:8]}")
    mode: BatchMode = BatchMode.PARALLEL
    tasks: list[TaskDefinition] = field(default_factory=list)
    max_concurrency: int = 5
    dependencies: list[str] = field(default_factory=list)
    timeout_seconds: int = 600


@dataclass
class ScheduleResult:
    """Result of batch execution by BatchScheduler.

    Contains aggregated results from all batches, including
    success/failure counts and individual Worker results.

    Attributes:
        success: Whether all batches completed without errors
        total_tasks: Total number of tasks across all batches
        completed_tasks: Number of successfully completed tasks
        failed_tasks: Number of failed tasks
        results: List of WorkerResult objects from all Workers
        duration_seconds: Total wall-clock execution time
        errors: List of error messages from failed tasks

    Example:
        >>> result = ScheduleResult(
        ...     success=True,
        ...     total_tasks=3,
        ...     completed_tasks=3,
        ...     failed_tasks=0,
        ...     duration_seconds=5.2,
        ... )
    """
    success: bool = False
    total_tasks: int = 0
    completed_tasks: int = 0
    failed_tasks: int = 0
    results: list[WorkerResult] = field(default_factory=list)
    duration_seconds: float = 0.0
    errors: list[str] = field(default_factory=list)


# ============================================================
# V3.7.0 "Anchor & Retrospect" Data Models
# ============================================================


class GoalItemStatus(Enum):
    """Coverage status of a goal item in retrospective analysis.

    Tracks how well each goal item was addressed during task execution.

    Attributes:
        PENDING: Goal item not yet addressed
        PARTIALLY_COVERED: Some progress made but incomplete
        FULLY_COVERED: Goal item completely satisfied
        EXCEEDED: Goal exceeded expectations
    """
    PENDING = "pending"
    PARTIALLY_COVERED = "partially_covered"
    FULLY_COVERED = "fully_covered"
    EXCEEDED = "exceeded"


class AnchorTrigger(Enum):
    """Events that trigger anchor checking.

    Defines when the AnchorChecker should verify alignment with goals.

    Attributes:
        STEP_COMPLETE: After each major step finishes
        PHASE_GATE: At phase transition points
        DIRECTION_CHANGE: When execution direction changes significantly
        CONFLICT: When conflict is detected between Workers
        MILESTONE: At predefined milestone markers
    """
    STEP_COMPLETE = "step_complete"
    PHASE_GATE = "phase_gate"
    DIRECTION_CHANGE = "direction_change"
    CONFLICT = "conflict"
    MILESTONE = "milestone"


class DriftSeverity(Enum):
    """Severity level of goal drift detection.

    Categorizes how much execution has deviated from original goals.

    Attributes:
        NONE: No drift detected (perfect alignment)
        LOW: Minor deviation, within acceptable tolerance
        MEDIUM: Moderate drift, may need attention
        HIGH: Significant drift, corrective action recommended
        CRITICAL: Severe drift, immediate intervention required
    """
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class GoalItem:
    """Individual item within a structured goal.

    Represents one specific objective to be tracked and measured
    for coverage during task execution.

    Attributes:
        item_id: Unique identifier for this goal item
        description: Human-readable description of the goal
        keywords: List of keywords for automatic matching (default: empty)
        status: Current coverage status (default: PENDING)
        coverage_score: Coverage level 0.0-1.0 (default: 0.0)
        evidence: List of evidence strings proving coverage (default: empty)
    """
    item_id: str
    description: str
    keywords: list[str] = field(default_factory=list)
    status: GoalItemStatus = GoalItemStatus.PENDING
    coverage_score: float = 0.0
    evidence: list[str] = field(default_factory=list)


@dataclass
class StructuredGoal:
    """Structured goal with multiple trackable items.

    Represents a high-level goal decomposed into measurable items
    for anchor checking and retrospective analysis.

    Attributes:
        goal_id: Unique identifier for this goal
        original_description: Original user-provided goal description
        items: List of GoalItem objects to track (default: empty)
        created_at: ISO format timestamp of creation

    Properties:
        overall_coverage: Average coverage across all items (0.0-1.0)
        uncovered_items: List of items not yet fully covered
    """
    goal_id: str = ""
    original_description: str = ""
    items: list[GoalItem] = field(default_factory=list)
    created_at: str = ""

    @property
    def overall_coverage(self) -> float:
        """Calculate average coverage score across all goal items.

        Returns:
            Float from 0.0 (no coverage) to 1.0 (fully covered).
            Returns 0.0 if no items exist.
        """
        if not self.items:
            return 0.0
        return sum(i.coverage_score for i in self.items) / len(self.items)

    @property
    def uncovered_items(self) -> list[GoalItem]:
        """Get list of goal items that are not yet fully covered.

        Returns items with PENDING or PARTIALLY_COVERED status.

        Returns:
            List of GoalItem objects needing more work.
        """
        return [i for i in self.items if i.status in (GoalItemStatus.PENDING, GoalItemStatus.PARTIALLY_COVERED)]


@dataclass
class DriftItem:
    """Single drift detection result.

    Describes one instance of goal misalignment detected during
    anchor checking.

    Attributes:
        content: Description of the detected drift
        severity: Severity level (default: LOW)
        reason: Explanation of why this is considered drift
    """
    content: str
    severity: DriftSeverity = DriftSeverity.LOW
    reason: str = ""


@dataclass
class AnchorResult:
    """Result of an anchor check (goal alignment verification).

    Produced by AnchorChecker to verify that execution remains
    aligned with the original structured goal.

    Attributes:
        aligned: Whether execution is aligned with goals (default: True)
        trigger: What event triggered this anchor check (default: STEP_COMPLETE)
        coverage: Current goal coverage level 0.0-1.0 (default: 1.0)
        drift_score: Accumulated drift score (higher = more misalignment, default: 0.0)
        drifts: List of detected drift items (default: empty)
        uncovered_goals: List of goal item IDs not yet covered (default: empty)
        recommendation: Suggested corrective action (default: empty)
        checked_at: ISO format timestamp when check was performed

    Properties:
        severity: Computed DriftSeverity based on drift_score threshold
    """
    aligned: bool = True
    trigger: AnchorTrigger = AnchorTrigger.STEP_COMPLETE
    coverage: float = 1.0
    drift_score: float = 0.0
    drifts: list[DriftItem] = field(default_factory=list)
    uncovered_goals: list[str] = field(default_factory=list)
    recommendation: str = ""
    checked_at: str = ""

    @property
    def severity(self) -> DriftSeverity:
        """Compute drift severity from drift score.

        Maps numeric drift score to categorical severity:
        - < 0.1: NONE (perfect alignment)
        - < 0.2: LOW (minor deviation)
        - < 0.3: MEDIUM (moderate concern)
        - < 0.5: HIGH (significant issue)
        - >= 0.5: CRITICAL (urgent action needed)

        Returns:
            DriftSeverity enum value representing current drift level.
        """
        if self.drift_score < 0.1:
            return DriftSeverity.NONE
        elif self.drift_score < 0.2:
            return DriftSeverity.LOW
        elif self.drift_score < 0.3:
            return DriftSeverity.MEDIUM
        elif self.drift_score < 0.5:
            return DriftSeverity.HIGH
        return DriftSeverity.CRITICAL


@dataclass
class DeviationRecord:
    """Single deviation from original plan detected in retrospective.

    Records one instance where execution diverged from the expected path,
    with optional impact analysis and corrective suggestions.

    Attributes:
        step_description: Description of the step where deviation occurred
        deviation_type: Category of deviation (e.g., "scope_creep", "technical_debt")
        reason: Explanation of why the deviation happened
        impact: Assessment of the deviation's effect (default: empty)
        suggestion: Recommended corrective action (default: empty)
    """
    step_description: str
    deviation_type: str
    reason: str
    impact: str = ""
    suggestion: str = ""


@dataclass
class RetrospectiveReport:
    """Comprehensive retrospective analysis report.

    Generated by RetrospectiveEngine after task completion to capture
    lessons learned, deviations, and improvement opportunities.

    Attributes:
        task_goal: Original goal description
        goal_id: Associated structured goal ID
        deviations: List of detected deviations from plan (default: empty)
        redundant_steps: List of steps identified as redundant (default: empty)
        improvements: List of suggested improvements for next time (default: empty)
        anchor_check_count: Total number of anchor checks performed
        anchor_drift_count: Number of anchor checks that detected drift
        final_coverage: Final goal coverage score 0.0-1.0 (default: 1.0)
        summary: Executive summary of the retrospective (default: empty)
        created_at: ISO format timestamp of report creation

    Methods:
        to_dict(): Convert report to dictionary for JSON serialization
        to_markdown(): Generate Markdown formatted report for display
    """
    task_goal: str = ""
    goal_id: str = ""
    deviations: list[DeviationRecord] = field(default_factory=list)
    redundant_steps: list[str] = field(default_factory=list)
    improvements: list[str] = field(default_factory=list)
    anchor_check_count: int = 0
    anchor_drift_count: int = 0
    final_coverage: float = 1.0
    summary: str = ""
    created_at: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert report to dictionary for JSON serialization.

        Returns summary statistics rather than full details for compactness.

        Returns:
            Dictionary with key metrics and metadata.
        """
        return {
            "task_goal": self.task_goal,
            "goal_id": self.goal_id,
            "deviation_count": len(self.deviations),
            "redundant_step_count": len(self.redundant_steps),
            "improvement_count": len(self.improvements),
            "anchor_check_count": self.anchor_check_count,
            "anchor_drift_count": self.anchor_drift_count,
            "final_coverage": self.final_coverage,
            "summary": self.summary,
            "created_at": self.created_at,
        }

    def to_markdown(self) -> str:
        """Generate Markdown formatted report for display.

        Creates a human-readable Markdown document with sections for
        task info, deviations, and improvements.

        Returns:
            Multi-line string in Markdown format ready for rendering.
        """
        lines = [
            "# Retrospective Report",
            "",
            f"**Task**: {self.task_goal}",
            f"**Goal ID**: {self.goal_id}",
            f"**Final Coverage**: {self.final_coverage:.0%}",
            f"**Anchor Checks**: {self.anchor_check_count} (drifts: {self.anchor_drift_count})",
            "",
        ]
        if self.deviations:
            lines.append("## Deviations")
            for d in self.deviations:
                lines.append(f"- **{d.deviation_type}**: {d.reason}")
                if d.suggestion:
                    lines.append(f"  → {d.suggestion}")
            lines.append("")
        if self.improvements:
            lines.append("## Improvements for Next Time")
            for imp in self.improvements:
                lines.append(f"- {imp}")
            lines.append("")
        lines.append("---\n*Generated by RetrospectiveEngine V3.7.0*")
        return "\n".join(lines)
